#!/usr/bin/python
# coding: utf-8
import MySQLdb
import time
import sys, string, os
import urllib
import re
import json
import urllib2

conn = MySQLdb.connect(host="121.201.10.15",
		user='eagleeye',
		passwd='EYeapp$ea@2',
		db="db_rankapp",
		port=30013)




cur = conn.cursor()
conn.set_character_set('utf8')
# s = '\''
# MySQLdb.escape_string(s)
# conn.escape_string(s)
str_time = time.strftime('%Y-%m-%d %T', time.localtime(time.time()))

html = open('/Users/Levi/github/monitoringDataFromItuneGame/14.7.30Paid/10.html', 'r')
hjson = json.loads(html.read())


if(hjson['results'][0].has_key('averageUserRating') == False):
	hjson_averageUserRating = 0
	hjson_userRatingCount = 0

else :
	hjson_averageUserRating = hjson['results'][0]['averageUserRating']
	hjson_userRatingCount = hjson['results'][0]['userRatingCount']

des = conn.escape_string(hjson['results'][0]['description'])
# print des

t = ("insert into tb_test (id, str, date) values ('11111', '%s', '%s' )" % (des, str_time))
# t = conn.escape_string(t)
# t = MySQLdb.escape_string(t);

	# .encode("gb2312","ignore")
	# print d.has_key('body')
	# print 'body' in d.keys()

	# cur.execute("insert into tb_app (app_id, app_name, author, app_Type, size, release_date, rom_type, description, icon_Url, trackViewUrl, download_url, \
	# filename, company_id, company_name, filemd5, star, created_at, updated_at, userRatingCount, bundleId, version, currency, price, channel_id) \
	# values ('%d', '%s', '%s', 0, '%s', '%s', 'null', '%s', '%s', '%s', 'null', 'null', '%d', '%s', \
	# 	'null', '%d', '%s', '%s', '%d', 'null', '%s', '%s', '%f', 0)" % (hjson['results'][0]['trackId'], hjson['results'][0]['trackName'], hjson['results'][0]['sellerName'] ,
	# 	hjson['results'][0]['fileSizeBytes'], hjson['results'][0]['releaseDate'], hjson['results'][0]['description'], hjson['results'][0]['artworkUrl60'], hjson['results'][0]['trackViewUrl'], 
	# 	hjson['results'][0]['artistId'], hjson['results'][0]['artistName'], hjson_averageUserRating, str_time, str_time, hjson_userRatingCount, hjson['results'][0]['version'], 
	# 	hjson['results'][0]['currency'], hjson['results'][0]['price'] ))


# t = ("insert into tb_app (app_id, app_name, author, app_Type, size, release_date, rom_type, description, icon_Url, trackViewUrl, download_url, \
# filename, company_id, company_name, filemd5, star, created_at, updated_at, userRatingCount, bundleId, version, currency, price, channel_id) \
# values ('%d', '%s', '%s', 0, '%s', '%s', 'null', '%s', '%s', '%s', 'null', 'null', '%d', '%s', \
# 	'null', '%d', '%s', '%s', '%d', 'null', '%s', '%s', '%f', 0)" % (hjson['results'][0]['trackId'], hjson['results'][0]['trackName'], hjson['results'][0]['sellerName'] ,
# 	hjson['results'][0]['fileSizeBytes'], hjson['results'][0]['releaseDate'], hjson['results'][0]['description'], hjson['results'][0]['artworkUrl60'], hjson['results'][0]['trackViewUrl'], 
# 	hjson['results'][0]['artistId'], hjson['results'][0]['artistName'], hjson_averageUserRating, str_time, str_time, hjson_userRatingCount, hjson['results'][0]['version'], 
# 	hjson['results'][0]['currency'], hjson['results'][0]['price'] ))
# print t
cur.execute(t)



	
conn.commit()
cur.close()
conn.close()



